version: '3.8'

services:
  ecommerce_tg_api:  # nokta ve Türkçe karakter yok
    build:
      context: .
      dockerfile: ECommerce_TG.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ECommerceTG;User=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
